/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 pen-v1.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pen-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-0.45, -0.07, 0.58]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.skin} rotation={[-0.23, -0.31, -2.38]} />
      </group>
    </group>
  )
}

useGLTF.preload('/pen-v1-transformed.glb')
