/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 poet-scroll-v1.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/poet-scroll-v1-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-2.19, 0.01, -2.04]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.skin} rotation={[-3.05, 0.64, 3.01]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/poet-scroll-v1-transformed.glb')
